homeassistant:
  # Name of the location where Home Assistant is running
  name: Pewaukee_Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named integrations




# Sensors
#sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml

switch: !include switch.yaml
light: !include light.yaml

binary_sensor: !include binary_sensor.yaml
cover: !include cover.yaml



#octoprint: !include octoprint.yaml
#insteon: !include insteon.yaml
#script: !include scripts.yaml



