esphome:
  name: crib_node
  platform: ESP32
  board: esp32doit-devkit-v1


wifi:
  ssid: !secret wifissid
  password: !secret wifipass
  power_save_mode: none
  manual_ip:
    static_ip: !secret crib_node_ip
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
    dns1: !secret ip_dns1

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable web server
web_server:
  port: 80

#esp32_ble_tracker:

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a
  
sensor:


  - platform: ccs811
    eco2:
      name: "CCS811 eCO2 Value"
    tvoc:
      name: "CCS811 Total Volatile Organic Compound"
    address: 0x5A
    update_interval: 60s

  - platform: bh1750
    name: "Crib Illuminance"
    measurement_time: 69
    update_interval: 60s

  - platform: wifi_signal
    name: Crib WiFi
    update_interval: 60s
    
    
  - platform: hx711
    name: "crib weight"
    id: crib_weight
    dout_pin: GPIO25
    clk_pin: GPIO26
    gain: 128
    filters:
      - calibrate_linear:
          - 2248 -> 0
          - 7248 -> 5.6
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
    update_interval: 60s
    unit_of_measurement: kg
    accuracy_decimals: 2
    
binary_sensor:
  - platform: template
    name: "Crib Occupancy "
    device_class: occupancy
    lambda: |-
      if (id(crib_weight).state > 5) {

        return true;
      } else {
        return false;
      }
  