substitutions:
  device_name: willow_tree_light
  device_description: 20W RGBWW flood light, West half of front yard facing the living room.
  friendly_name: Willow Tree Light ESP
  static_ip: !secret willow_tree_light_ip


<<: !include novoflood_common.yaml